---
title: "systemPipe: Workflow and Visualization Toolkit"
author: 
output: 
  rmarkdown::html_vignette: default
vignette: >
  %\VignetteIndexEntry{systemPipe: Workflow and Visualization Toolkit}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
---


```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

**Authors**:
    Daniela Cassol (danielac@ucr.edu),
    Le Zhang ("le.zhang001@email.ucr.edu"),
    Thomas Girke (thomas.girke@ucr.edu).
    
**Institution**: Institute for Integrative Genome Biology, University of California, Riverside, California, USA.

**Last modified**: 8 March, 2021.

# Overview

## Workshop Description

This workshop introduces _systemPipe_ (SP), a generic toolkit for designing and running reproducible data analysis workflows. The environment consists of three major modules implemented as R/Bioconductor packages. _systemPipeR_ (SPR) provides core functionalities for defining workflows, interacting with command-line software, and executing both R and/or command-line software, as well as generating publication-quality analysis reports. _systemPipeShiny_ (SPS) integrates a graphical user interface for managing workflows and visualizing results interactively. _systemPipeWorkflow_ (SPW) offers a collection of pre-configured workflow templates. This hand-on event will include the following topics: (1) brief overview of the design principles and functionalities of the SP toolkit; (2) configuration and execution of workflows; (3) design and usage of SPR's command-line interface based on an object-oriented R implementation of CWL; (4) construction of custom workflows; (5) parallel execution of workflows on HPC and cloud systems with and without schedulers; (6) generation of technical and scientific analysis reports including visualization; (7) configuration and execution of a pre-configured workflow example from start to finish, e.g. smallRNA-Seq template; and (8) demonstration of SPS' core functionalities, the project's Shiny App.

## Pre-requisites

  * Basic knowledge of R and usage of Bioconductor packages for NGS analysis
  * Basic knowledge of running command-line software
  * Basic knowledge of parallelization concepts


Non-essential background reading:

  * [systemPipe Workflow Environment](https://systempipe.org/)
  * [systemPipeR vignette](https://bioconductor.org/packages/devel/bioc/vignettes/systemPipeR/inst/doc/systemPipeR.html)
  * [systemPipeShiny vignette](https://bioconductor.org/packages/devel/bioc/vignettes/systemPipeShiny/inst/doc/systemPipeShiny.html)
  * [systemPipeRdata vignette](https://bioconductor.org/packages/release/data/experiment/vignettes/systemPipeRdata/inst/doc/systemPipeRdata.html)
  * [R Markdown tutorial](https://rmarkdown.rstudio.com/lesson-2.html)

## Workshop Participation

Participants will be able to perform all analysis components of this workshop hands-on. Active user participation throughout the event is highly encouraged, including but not limited to lecture material, hands-on sections, and final discussion about package improvements. Participants are encouraged to ask questions at any time during the workshop.

## _R_ / _Bioconductor_ packages used

* [`systemPipeR`](http://www.bioconductor.org/packages/release/bioc/html/systemPipeR.html)
* [`systemPipeShiny`](https://bioconductor.org/packages/devel/bioc/html/systemPipeShiny.html)
* [`systemPipeRdata`](http://www.bioconductor.org/packages/release/data/experiment/html/systemPipeRdata.html)
* [R Markdown tutorial](https://rmarkdown.rstudio.com/lesson-2.html)

## Time outline

1h 45m total

| Activity                                                          | Time |
|-------------------------------------------------------------------|------|
| Introduction                                                      | 5m   |
| Overview of *systemPipeR* package                                 | 10m  |
| Introduction to new S4 class: `SYSargs2` and `SYSargsList`        | 20m  |
| Showcase small RNA-Seq workflow                                   | 20m  |
| Parallelization on single machines and clusters                   | 10m  |
| Building a custom workflow                                        | 20m  |
| Overview of *systemPipeShiny* package                             | 20m  |

## Workshop goals and objectives

### Learning goals

* Recognize the benefits of a generic R-based workflow construction environment that is both scalable and reproducible
* Integration of command-line tools via the CWL community standard
* Rendering of R markdown reports and critical assessment of scientific analysis reports
* Parallelization of big data analysis tasks

### Learning objectives

* Identify and practice how to make analysis workflows more robust, reproducible, and portable across heterogeneous computing systems
* Usage of new workflow control class for designing, configuring, and running workflows
* Optimize and debug workflows
* Inspection of technical reports and log files
* Design of new and fully customized workflows
* Practice interactive workflow management and visualization 


# Workshop

## Workshop setup with Docker


